modLoader="javafml"
loaderVersion="[2,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''Magical automation or smth idk'''

[[mixins]]
config="arcane.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="[${neoforge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
